### ISSUE TITLE
run demo show error

### ISSUE THREAD

**Issue by atlas1119** [DickyT/react-native-tabbar-navigator#1]
npm start   run   error

/Users/wsj/project/react-native-tabbar-navigator/TabBarNavigatorExample/node_modules/react-native/packager/packager.js:15
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

why?

**Comment by DickyT** [comment]
If you are going to run the example, you can just open the Xcode Project and run. And no `npm start` required. If the problem still exists, try `npm init TabBarNavigatorExample` then install this package, and replace the new index.ios.js with the existing one. I will try to fix this issues later. Thank you for your issue.

**Comment by DickyT** [comment]
@atlas1119 Hi I just tested the example and I could not re-show your issue. And I just added the detailed instruction on How to run the example App on README, and you can also check the new link on React Native Playground.
