### ISSUE TITLE
Integrating with react-native-vector-icons?

### ISSUE THREAD

**Issue by marketman400** [DickyT/react-native-tabbar-navigator#10]
Hope finals went well.  Any chance you can add support for https://github.com/oblador/react-native-vector-icons for the tabbar?

**Comment by DickyT** [comment]
@marketman400 Thanks for opening this issue, i will take a look after my university's final :-(

**Comment by marketman400** [comment]
Thanks and good luck!

**Comment by DickyT** [comment]
@marketman400 Hi, I took a look at the `react-native-vector-icons` project, which it only displays the icons in text(?) , but not in image format, but the TabBarIOS object only accept image as the tab icons. Whats more, the TabBarIOS is an native component, it is hard to modify it

**Comment by DickyT** [comment]
@marketman400 I got a excellent website, which can generate base64 icons for tabbar, thats really convenience. http://fa2png.io/

**Comment by marketman400** [comment]
Thanks for looking into this and nice find to generate icons!
