### ISSUE TITLE
Updating the NavBar items

### ISSUE THREAD

**Issue by rahuljiresal** [DickyT/react-native-tabbar-navigator#11]
Many times, I wanted to update the NavBar items upon some action in the underlying component. I tried everything, but `Navigator.NavigationBar` did not let me update.

Also, with React Native 0.15, the ability to have an action on title of a pushed route is not possible. This is due to a bug in RN15.

Probably using https://github.com/react-native-fellowship/react-native-navbar instead of `Navigator.NavigationBar` is a better option.

**Comment by DickyT** [comment]
I just take a look on this project, does this `react-native-navbar` support the `push` operation?

**Comment by DickyT** [comment]
because I did not see anything about this, I think it is just a pure navigation bar?

**Comment by rahuljiresal** [comment]
It is just a pure navigation bar. But you can add it as a sub-component to the component that is being pushed to the navigation stack. The good thing about it is, it gets re-rendered whenever you want.

**Comment by marketman400** [comment]
I've been able to update my NavBar using a function that calls forceReRender():

  enableNextLink() {
    this.props.navComponent.forceReRender(
      this.props.navComponent.setNavItems({ ...

**Comment by DickyT** [comment]
@rahuljiresal @marketman400 does it supports animations while you are swiping back?

**Comment by marketman400** [comment]
@DickyT I have not tried animations yet.

**Comment by rahuljiresal** [comment]
@dickyt it totally supports it. The views are still pushed using the Navigator. It just doesn't use Navigator.NavigationBar. Navigator has swipe animations out of the box, doesn't depend on the NavigationBar. 

Check out my other project https://github.com/rahuljiresal/react-native-rj-navigator

**Comment by DickyT** [comment]
I worked it out, and I can release a new version after bugs are fixed.

**Comment by DickyT** [comment]
@rahuljiresal latest version fixed
