### ISSUE TITLE
regarding passProps at   this.props.navigator.push

### ISSUE THREAD

**Issue by YanzhuVAS** [DickyT/react-native-tabbar-navigator#12]
Hi Dicky,

I had one problem when switch the TabBarIOS to your TabBarNavigator,
passProps seems not working , the component pushed not able to get the props . 
I checked your source code, seems you used the navigator as the base class, the this article said
it is not suppored to pass props to next component when push,  could you provide a fix or any other suggestion in this case?

```
  this.props.navigator.push({
    title: 'Results',
    component: <CargoTableView/>,
    passProps: {listings: response.listings}
  });
```

**Comment by YanzhuVAS** [comment]
https://github.com/react-native-fellowship/react-native-navbar/issues/15 is the article referred.

**Comment by YanzhuVAS** [comment]
I found the solution:

  this.props.navigator.push({
        title: 'Results',
        component: <CargoTableView listings={ response.listings}/>
      });

works under my case.

**Comment by YanzhuVAS** [comment]
this.props.navigator.push({
        title: 'Results',
        component: <CargoTableView listings={ response.listings}/>
      });

**Comment by YanzhuVAS** [comment]
```
  this.props.navigator.push({
    title: 'Results',
    component: <CargoTableView listings={ response.listings}/>
  });
```

works for me

**Comment by DickyT** [comment]
Yes, you are right
