### ISSUE TITLE
push a new page Error

### ISSUE THREAD

**Issue by bluesky0109** [DickyT/react-native-tabbar-navigator#13]
点击 try to push a new page 后报错如图所示
![b1ea1f3b-ee4c-4fb9-b1b1-d51d674292ed](https://cloud.githubusercontent.com/assets/8929364/12529114/090ac234-c1e8-11e5-8725-f835dbea1660.png)

使用的 react-native版本为 0.18.1

**Comment by DickyT** [comment]
@bluesky0109 你试下用`npm i DickyT/react-native-tabbar-navigator`装多次, master里面没看到有这个变量...
