### ISSUE TITLE
如何在组件mount之后修改顶部的组件？

### ISSUE THREAD

**Issue by fakefish** [DickyT/react-native-tabbar-navigator#16]
push一个页面的时候会把前面那个页面没渲染出来的组件渲染出来

**Comment by DickyT** [comment]
这个问题还没找到完美解决办法, 暂时能用的就是在constructor里面直接设置当前的顶部组件, 第一次render之后的修改就生效不了了, 会留到下次push再渲染

**Comment by DickyT** [comment]
@fakefish latest version fixed
