### ISSUE TITLE
如何动态修改导航栏的颜色？

### ISSUE THREAD

**Issue by bluesky0109** [DickyT/react-native-tabbar-navigator#18]
比如页面是一个scrollview，进入页面导航为透明色，根据scrollview滑动的距离 逐步变化导航栏的颜色、能提供对应的接口吗？？
另外问一个问题 
![image](https://cloud.githubusercontent.com/assets/8929364/13275203/5eb1480c-daed-11e5-8d37-f74e99bbce3b.png) 类似这种 导航栏左侧或右侧有多个按钮的 能定制吗？？

**Comment by DickyT** [comment]
1. You can customize your own `Navigator.NavigationBar` and attach events on it.
2. `rightItem` is a component, you can use a customized component, and not passing `onPress` in route, and define your own event inside your component.
