### ISSUE TITLE
push页面时 passProps传递的接受不到

### ISSUE THREAD

**Issue by bluesky0109** [DickyT/react-native-tabbar-navigator#19]
pushPage() {
    this.props.navigator.push({
      title: 'New Page',
      component: <NewPage/>,
      passProps:{a:0,b:1}
    });
  }

在下个页面 获取不到上个页面传递的 参数

**Comment by DickyT** [comment]
用法错啦应该是
pushPage() {
this.props.navigator.push({
title: 'New Page',
component: <View first='' second='' c=''/>,
});
}

**Comment by DickyT** [comment]
```
pushPage() {
this.props.navigator.push({
title: 'New Page',
component: <View a='' b=''/>,
});
}
```
