### ISSUE TITLE
Ability to hide title bar by default

### ISSUE THREAD

**Issue by varqasim** [DickyT/react-native-tabbar-navigator#20]
Is it possible to hide the title bar area when pushed or even by default. I want all my tabs to have no title area at the top.

**Comment by DickyT** [comment]
you mean show the logo only in tab bar area? or hide the whole tab bar?

**Comment by varqasim** [comment]
@DickyT Hide the whole bar.

**Comment by DickyT** [comment]
if u gonna hide the whole bar, you can just use the `<Navigator/>` or `<NavigatorIOS/>` in react-native.
https://facebook.github.io/react-native/docs/navigator.html
https://facebook.github.io/react-native/docs/navigatorios.html
