### ISSUE TITLE
关于更新使得这个组件匹配0.18.0之后的 rn 版本

### ISSUE THREAD

**Issue by hainuo** [DickyT/react-native-tabbar-navigator#24]
RT 匹配最新的 Rn 版本

**Comment by BTMouseKing** [comment]
This is a great component, but looks like it's not compatible with the new RN versions. I'm getting "access 'ReactNative.Component' from the 'react-native' package" issue, can anyone fix this please?

**Comment by DickyT** [comment]
@BTMouseKing I am back, in progress to support latest RN, thanks for support, busying for half year before because of my university stuffs

**Comment by DickyT** [comment]
0.4.0 is released, closing this
