### ISSUE TITLE
For Android

### ISSUE THREAD

**Issue by fselcukcan** [DickyT/react-native-tabbar-navigator#8]
In the react.parts website your component is listed as For iOS and For Android.
But in the repo README it is mentioned as iOS only at the title.
Also in the npm it is not mentioned at all.
What is it?
By the way thanks for the effort.
I would like to see this as cross paltform, and planning to try it.

**Comment by DickyT** [comment]
Hi there, I just went to react.parts and I think they made a mistake, and I just know a little bit about android, and I have no Android devices, so this package have no Android version, sorry for that.

**Comment by fselcukcan** [comment]
I have gone through your code and in the Require statements I can see no other iOS specific ReactNative component than `TabBarIOS`.
I think one can write own tabbar RN component and give it to `MainTabBar` of your library. As far as I see, `MainTabBar` consumes RN `TabBarIOS` in the `MainTabBar.renderTabBarItems` and `MainTabBar.render`. I mean `TabBarIOS` is hardcoded inside it. By `MainTabBar` having a Tabbar property, some custom component can be given to it.

Can it be achieved so, by a custom implemented TabBar? That would make the library cross-platform.

**Comment by DickyT** [comment]
Yes, but I want to make this package have a perfect native solution on iOS so I have to use the `TabBarIOS`, maybe I can implement an Android version once I am free. I am now suffered in the final exam stuffs on university, I might be little bit hard these days. And if you want to create PR, it is very welcome.

**Comment by fselcukcan** [comment]
Ok, got it. If I do something useful I will notify. Good grades in your finals.

**Comment by DickyT** [comment]
Thank you ^_^

**Comment by fselcukcan** [comment]
How do you actually `hidesBottomBarWhenPushed`?
I could not find any references to an entity like that in your source code, as far as I remember.

**Comment by DickyT** [comment]
Hi, I use a `<Navigator/>` to wrap a `<TabBarIOS/>` inside it.
